version: "3.7"
services:
  zabbix:
    image: "test-zabbix"
    environment:
      - POSTGRES_PASSWORD=Y9PdtjyP9tvD
      - POSTGRES_DB=alperdb
      - POSTGRES_USER=alperensah
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data
    - data:/data
    dns:
    - 8.8.8.8
    - 8.8.4.4

volumes:
  db:
  data: